name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  watch: # 3.手动点击收藏
    types: [started]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25b
        add-to-path: true
        local-cache: true
        
    - name: Build
      run: ./build.sh
    
    - name: Collect artifcat name
      run: |
        echo "release=$(basename -s .zip build/*.zip)" >> $GITHUB_ENV

    - name: Upload Release
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.release }}
        path: magisk
